// Spec 10 §7.2 变异矩阵（桌面端 TS 侧）。纯数据：锚点逐字、在该文件内唯一；多处编辑用 edits。
// Python 侧的 MUT-18~21、53、54 在 scripts/verify_mutations.py（S10-MUT-*），不在这里。
// targets：{ vitest: [...] }（空数组 = 全量 vitest，约 10 s）或 { e2e, grep }（Playwright 单条）。
// expect：矩阵「变红」列的用例编号；harness 按编号核对失败名单（KILLED 须全部命中）。
// 与矩阵机理不同的变体在 note 里写明（回填时如实登记）。

const ALL = { vitest: [] };
// e2e 目标优先指真实 core 版（sessionReal.spec.ts）：断言更全，也是 PR4 的主体；只有 TX-1 的
// 「伪造 answer JSON 不生成按钮」这类纯渲染断言用假进程版就够
const e2e = (grep, file = "e2e/session.spec.ts") => ({ e2e: file, grep });
const real = (grep) => e2e(grep, "e2e/sessionReal.spec.ts");

const SESS = "src/host/sessions.ts";
const SVC = "src/host/service.ts";
const MAIN = "src/main/index.ts";
const CARDS = "src/renderer/HumanCards.tsx";
const CONVP = "src/renderer/ConversationPane.tsx";
const AUTO = "src/renderer/autoOpen.ts";
const APP = "src/renderer/App.tsx";
const FIX = "tests/fixtures/session.ts";

export const MUTATIONS = [
  { id: "MUT-1", guard: "懒启动：打开期不 spawn 会话", expect: ["TH-1"], targets: [ALL], file: SVC,
    old: "    this.active = e.epKey;\n    return this.withLoad(rt, async () => {\n",
    new: "    this.active = e.epKey;\n    void (this.sessions as unknown as { ensure: (k: string, t: unknown) => Promise<unknown> }).ensure(`ep:${e.epKey}`, this.convTarget(`ep:${e.epKey}`, \"new\")).catch(() => undefined); // MUT-1\n    return this.withLoad(rt, async () => {\n" },
  { id: "MUT-2", guard: "只读 stdout（stderr 不解析，H-9）", expect: ["TH-2"], targets: [ALL], file: SESS,
    old: "      if (s.procGen !== gen) return;\n      const all = s.stderrTail",
    new: "      if (s.procGen !== gen) return;\n      this.onStdout(s, chunk); // MUT-2\n      const all = s.stderrTail" },
  { id: "MUT-3", guard: "answer 先查打开集合", expect: ["TH-3"], targets: [ALL], file: SESS,
    old: "    const req = s?.openIds.get(requestId);\n    if (!s || !req) this.fail(\"E_STALE\", \"该请求已关闭或不存在\");\n",
    new: "    const req = (s?.openIds.get(requestId) ?? { t: \"request\", options: [decision], kind: \"tool_call\", feedback_allowed: true }) as unknown as OutFrame; // MUT-3\n    if (!s) this.fail(\"E_STALE\", \"该请求已关闭或不存在\");\n" },
  { id: "MUT-4", guard: "进程退出清空打开集合（H-5）", expect: ["TH-4", "TX-9"], targets: [ALL, real("TX-9 ")], file: SESS,
    old: "    if (s.open.length > 0) {\n      const ids = s.open.map((o) => String(o.request_id));\n      s.open = [];\n      s.openIds.clear();\n",
    new: "    if (false) { // MUT-4\n      const ids = s.open.map((o) => String(o.request_id));\n      s.open = [];\n      s.openIds.clear();\n" },
  { id: "MUT-5", guard: "host 从不代发 user_message（H-8）", expect: ["TH-5"], targets: [ALL], file: SESS,
    old: "        this.registerSettle(s, String(f.turn_id));\n",
    new: "        this.registerSettle(s, String(f.turn_id));\n        this.writeFrame(s, { v: 1, t: \"user_message\", text: \"继续\", rid: this.rid() }); // MUT-5\n" },
  { id: "MUT-6", guard: "密钥不进诊断", expect: ["TH-6"], targets: [ALL], file: SESS,
    old: "    else extraEnv[keyInfo.name] = keyInfo.value;\n",
    new: "    else {\n      extraEnv[keyInfo.name] = keyInfo.value;\n      this.deps.diag(`已注入 ${keyInfo.name}=${keyInfo.value}`); // MUT-6\n    }\n" },
  { id: "MUT-7", guard: "只有 SESSION_* 带密钥变量", expect: ["TH-6"], targets: [ALL],
    edits: [
      { file: "src/host/spawner.ts", old: "    env: { ...childEnv(process.env), ...extraEnv },", new: "    env: { ...childEnv(process.env), ...(((globalThis as Record<string, unknown>).__mut7 = extraEnv), extraEnv) }, // MUT-7" },
      { file: "src/host/spawner.ts", old: "childEnv(process.env, homebrewPath === true), stdoutMax, stdinData);", new: "{ ...childEnv(process.env, homebrewPath === true), ...(((globalThis as Record<string, unknown>).__mut7 as Record<string, string>) ?? {}) }, stdoutMax, stdinData); // MUT-7" },
    ] },
  { id: "MUT-8", guard: "security 输出只去恰好一个末尾换行", expect: ["TV-8"], targets: [ALL], file: "src/shared/secretsRules.ts",
    old: "  const v = stdout.endsWith(\"\\n\") ? stdout.slice(0, -1) : stdout;", new: "  const v = stdout.replace(/\\s+$/, \"\"); // MUT-8" },
  { id: "MUT-9", guard: "密钥变量名白名单（不只查大写）", expect: ["TV-9"], targets: [ALL], file: "src/shared/secretsRules.ts",
    old: "  return KEY_ENV_NAME_RE.test(name);", new: "  return /^[A-Z_]+$/.test(name); // MUT-9" },
  { id: "MUT-10", guard: "interrupt 核对当前 turnId", expect: ["TH-8"], targets: [ALL], file: SESS,
    old: "    if (!s || s.turnId !== turnId) this.fail(\"E_STALE\", \"该回合已结束或不匹配\");",
    new: "    if (!s) this.fail(\"E_STALE\", \"该回合已结束或不匹配\"); // MUT-10" },
  { id: "MUT-11", guard: "结束序列 SIGTERM 只发会话 pid", expect: ["TH-9"], targets: [ALL], file: SESS,
    old: "    s.proc.signal(\"SIGTERM\", false);\n    const grace", new: "    s.proc.signal(\"SIGTERM\", true); // MUT-11\n    const grace" },
  { id: "MUT-12", guard: "结束序列宽限后 SIGKILL 整组", expect: ["TH-9"], targets: [ALL], file: SESS,
    old: "    if (s.pid !== null) this.deps.killGroup(s.pid);\n    return { code: null, signal: \"SIGKILL\" };",
    new: "    // MUT-12：省掉 SIGKILL\n    return { code: null, signal: \"SIGKILL\" };" },
  { id: "MUT-13", guard: "resetRenderer 不结束会话", expect: ["TH-10"], targets: [ALL], file: SVC,
    old: "  resetRenderer(): void {\n    this.subs.clear();\n", new: "  resetRenderer(): void {\n    void this.sessions.stopAllForQuit(); // MUT-13\n    this.subs.clear();\n" },
  { id: "MUT-14", guard: "退出码 3 → E_SESSION_LOCKED", expect: ["TH-11b"], targets: [ALL], file: SESS,
    old: "  if (code === 3) return new SessionError(\"E_SESSION_LOCKED\"", new: "  if (code === 3) return new SessionError(\"E_SESSION\" /* MUT-14 */" },
  { id: "MUT-15", guard: "完整行也查长度上限", expect: ["TH-12"], targets: [ALL], file: SESS,
    old: "      if (Buffer.byteLength(line, \"utf-8\") > SESSION_FRAME_MAX_BYTES) {", new: "      if (false) { // MUT-15" },
  { id: "MUT-16", guard: "有活会话时拒绝切换仓库", expect: ["TH-13"], targets: [ALL], file: SVC,
    old: "    if (this.sessions.anyLive()) throw new RpcFail(\"E_BUSY\", \"存在活会话，先结束全部会话再切换仓库\");\n", new: "    // MUT-16\n" },
  { id: "MUT-17", guard: "建期失败时 host 零写入", expect: ["TG-2", "TH-14"], targets: [ALL], file: SVC,
    old: "    if (r.code !== 0) throw new RpcFail(\"E_CORE\", `建期失败（",
    new: "    if (r.code !== 0) require(\"node:fs\").mkdirSync(`${this.repoRoot}/data/episodes/${name}`, { recursive: true }); // MUT-17\n    if (r.code !== 0) throw new RpcFail(\"E_CORE\", `建期失败（" },
  { id: "MUT-22", guard: "决策卡批准：首句 isTrusted", expect: ["TG-4′", "TX-2"], targets: [ALL, real("TX-2 ")], file: CARDS,
    old: "            if (!e.nativeEvent.isTrusted) return;\n            void run(obj, rpc.call(\"approval.decide\", approveParams)",
    new: "            void run(obj, rpc.call(\"approval.decide\", approveParams)" },
  { id: "MUT-23", guard: "无批量批准（.map 里调 conv.answer）", expect: ["TG-4′"], targets: [ALL], file: CARDS,
    old: "      <div className=\"ui-card-actions\">\n        {options.map((decision) => (",
    new: "      <div className=\"ui-card-actions\">\n        <button onClick={(e) => { if (!e.nativeEvent.isTrusted) return; [requestId].map((id) => rpc.call(\"conv.answer\", { convKey, requestId: id, decision: \"approve\" })); }}>全部批准</button>\n        {options.map((decision) => (" },
  { id: "MUT-23b", guard: "无批量批准（具名函数 + forEach）", expect: ["TG-4′"], targets: [ALL], file: CARDS,
    old: "      <div className=\"ui-card-actions\">\n        {options.map((decision) => (",
    new: "      <div className=\"ui-card-actions\">\n        <button onClick={(e) => { if (!e.nativeEvent.isTrusted) return; const a = (id: string) => rpc.call(\"conv.answer\", { convKey, requestId: id, decision: \"approve\" }); [requestId].forEach(a); }}>全部批准</button>\n        {options.map((decision) => (" },
  { id: "MUT-24", guard: "conv.answer 只在 HumanCards 的 onClick 里", expect: ["TG-4′"], targets: [ALL], file: CONVP,
    old: "export function ConversationPane({ rows }: { rows: ConvRow[] }) {\n",
    new: "export function __mut24(rpc: { call: (m: string, p: unknown) => unknown }): void { useEffect(() => { void rpc.call(\"conv.answer\", {}); }, []); } // MUT-24\nexport function ConversationPane({ rows }: { rows: ConvRow[] }) {\n",
    note: "只植入静态形状（未接进组件）：TX-2 的「无点击出现 answer」需要真的被调用，这里不期望它红" },
  { id: "MUT-25", guard: "助手回复不用 markdown-it", expect: ["TG-13"], targets: [ALL], file: CONVP,
    old: "import { Icon } from \"./icons\";\n", new: "import { Icon } from \"./icons\";\nimport MarkdownIt from \"markdown-it\"; // MUT-25\nvoid MarkdownIt;\n" },
  { id: "MUT-26", guard: "助手文本里的「批准」不生成按钮（H-2）", expect: ["TX-1"], targets: [real("TX-1 ")], note: "假进程版 TX-1 只在待答区内数按钮（spec 要求整页），变异生成的按钮在对话流里，范围之外；真实 core 版按整页数", file: CONVP,
    old: "          {label && <span className=\"conv-label\" data-testid=\"conv-label\">{label}</span>}\n          {row.text}\n",
    new: "          {label && <span className=\"conv-label\" data-testid=\"conv-label\">{label}</span>}\n          {row.text}\n          {/\\[批准\\]/.test(row.text) && <button data-testid=\"request-answer-approve\">批准</button>}\n" },
  { id: "MUT-27", guard: "人占用预览时不替换（owner）", expect: ["TV-6", "TX-5"], targets: [ALL, real("TX-5 ①②④")], file: AUTO,
    old: "  if (s.owner === \"human\" || env.mediaPlaying)", new: "  if (env.mediaPlaying) // MUT-27\n " },
  { id: "MUT-28", guard: "回合进行中只登记不呼出", expect: ["TV-6", "TX-5"], targets: [ALL, real("TX-5 ③")], file: AUTO,
    old: "      if (s.awaiting !== null) {", new: "      if (false) { // MUT-28" },
  { id: "MUT-29", guard: "结算后每类只呼出最新者", expect: ["TV-6"], targets: [ALL], file: AUTO,
    old: "      return applyCandidate(cleared, latest(cands), env);", new: "      return applyCandidate(cleared, cands[0], env); // MUT-29",
    note: "变体：按到达顺序取第一个（非最新），而非矩阵的「呼出两次」——现实现的 settled 分支一次只能返回一个候选" },
  { id: "MUT-30", guard: "自动呼出 / 已就绪条不移焦", expect: ["TX-5"], targets: [real("TX-5 ①②④")], file: APP,
    old: "      setStrip(r.state.strip);\n", new: "      setStrip(r.state.strip);\n      if (r.state.strip) (document.activeElement as HTMLElement | null)?.blur(); // MUT-30\n",
    note: "变体：出现「已就绪」条时移焦（blur）；PR3 偏差 2 已登记 TX-5④ 只覆盖已就绪条这一支" },
  { id: "MUT-31", guard: "convStore 按会话键分桶", expect: ["TV-4", "TX-6"], targets: [ALL, real("TX-6 ")], file: "src/renderer/convStore.ts",
    old: "      return { store: { convs: { ...store.convs, [d.convKey]: next } }, resnapshot: null };",
    new: "      return { store: { convs: Object.fromEntries(Object.keys({ ...store.convs, [d.convKey]: 1 }).map((k) => [k, k === d.convKey ? next : { ...store.convs[k], open: [...store.convs[k].open, ...d.open] }])) }, resnapshot: null }; // MUT-31" },
  { id: "MUT-32", guard: "失败 observation 逐字不截断", expect: ["TV-2", "TX-1"], targets: [ALL, real("TX-1 ")], file: "src/shared/convFold.ts",
    old: "          row.observation = (f.observation as string | null) ?? null;", new: "          row.observation = ((f.observation as string | null) ?? null)?.slice(0, 500) ?? null; // MUT-32" },
  { id: "MUT-33", guard: "时间线：无 approval_id 按 decision 标", expect: ["TV-7", "TX-11"], targets: [ALL, real("TX-11 ")], file: "src/shared/fold.ts",
    old: "      const verdict = decision === \"approved\" ? \"批准\"", new: "      const verdict = decision === \"__never\" ? \"批准\" /* MUT-33 */" },
  { id: "MUT-34", guard: "建期表单初值为空串字面量", expect: ["TG-15"], targets: [ALL], file: "src/renderer/NewEpisodeForm.tsx",
    old: "useState(\"\")", new: "useState(String(\"\")) /* MUT-34 */" },
  { id: "MUT-35", guard: "建期后不把 idea 讨论发给新期", expect: ["TX-7"], targets: [real("TX-7 ")], file: SVC,
    old: "    this.refreshEpisodes();\n    this.push({ v: 1, kind: \"push\", topic: \"episodes.summary\", data: this.episodesList() });\n    return { epKey: name };",
    new: "    this.refreshEpisodes();\n    this.push({ v: 1, kind: \"push\", topic: \"episodes.summary\", data: this.episodesList() });\n    void this.sessions.send(`ep:${name}` as never, this.convTarget(`ep:${name}`, \"new\"), \"（选题讨论）\").catch(() => undefined); // MUT-35\n    return { epKey: name };" },
  { id: "MUT-36", guard: "host 写帧用无损序列化", expect: ["TG-9"], targets: [ALL], file: SESS,
    old: "    s.proc.write(`${stringifyLossless(frame)}\\n`);", new: "    s.proc.write(`${JSON.stringify(frame)}\\n`); // MUT-36" },
  { id: "MUT-37", guard: "error 帧按 rid 归属", expect: ["TH-17"], targets: [ALL], file: SESS,
    old: "        const rid = ridOf(f);\n        if (rid) {\n          const mapped",
    new: "        const rid = ridOf(f) ?? [...s.sendWaiters.keys()][0] ?? null; // MUT-37\n        if (rid) {\n          const mapped" },
  { id: "MUT-38", guard: "SESSION_* 的 stdin 是 pipe", expect: ["TH-1"], targets: [ALL], file: "src/host/spawner.ts",
    old: "    stdio: [\"pipe\", \"pipe\", \"pipe\"],\n    detached: true,", new: "    stdio: [\"ignore\", \"pipe\", \"pipe\"], // MUT-38\n    detached: true," },
  { id: "MUT-39", guard: "有忙会话时退出先弹确认", expect: ["TX-8"], targets: [real("TX-8 真实")], file: MAIN,
    old: "        if (m.busy.length === 0) {", new: "        if (true) { // MUT-39" },
  { id: "MUT-40", guard: "desktop/src 不读 session.jsonl", expect: ["TG-14"], targets: [ALL], file: SESS,
    old: "const STDERR_TAIL_BYTES = 8 * 1024;\n", new: "const STDERR_TAIL_BYTES = 8 * 1024;\nconst MUT40 = \"session.jsonl\"; // MUT-40\nvoid MUT40;\n" },
  { id: "MUT-41", guard: "会话 pid 退出后清理进程组", expect: ["TH-9"], targets: [ALL], file: SESS,
    old: "    if (s.pid !== null && this.deps.groupAlive(s.pid)) this.deps.killGroup(s.pid); // 进程组清理（§2.10）\n", new: "    // MUT-41\n" },
  { id: "MUT-42", guard: "夹具写入守卫（realpath + lstat）", expect: ["TF-1"], targets: [{ vitest: ["tests/host/sessionFixtures.test.ts"] }], file: FIX,
    old: "    if (st.isSymbolicLink()) throw new Error(`fixtureWrite 路径组件是符号链接，拒绝写入：${cur}`);\n    const real = fsw.realpathSync(cur);\n    if (real !== rootReal && !real.startsWith(rootReal + sep)) throw new Error(`fixtureWrite 路径经符号链接越出临时根：${cur}`);\n",
    new: "    // MUT-42：夹具改回可经软链写穿（只以 TF-1 的诱饵受控实跑）\n",
    note: "只跑 TF 夹具自检文件：TF-1 已改用根外诱饵 .venv（M9），守卫失效也碰不到真实解释器" },
  { id: "MUT-43", guard: "抓取卡批准须过原生确认框", expect: ["TH-18", "TX-13"], targets: [ALL, real("TX-12b/TX-13")], file: SESS,
    old: "      if (needsNativeConfirm(req, decision)) {", new: "      if (false && needsNativeConfirm(req, decision)) { // MUT-43" },
  { id: "MUT-44", guard: "rpc.call 首参是方法字面量", expect: ["TG-16"], targets: [ALL], file: CARDS,
    old: "import { Icon } from \"./icons\";\n", new: "import { Icon } from \"./icons\";\nexport function __mut44(rpc: { call: (m: string, p?: unknown) => unknown }): unknown { const m = \"conv.answer\"; return rpc.call(m, {}); } // MUT-44\n" },
  { id: "MUT-45", guard: "onClick 只挂在小写原生标签上", expect: ["TG-4′"], targets: [ALL],
    edits: [
      { file: CARDS, old: "          <button\n            key={decision}", new: "          <CardButton\n            key={decision}" },
      { file: CARDS, old: "            {DECISION_LABEL[decision] ?? decision}\n          </button>", new: "            {DECISION_LABEL[decision] ?? decision}\n          </CardButton>" },
      { file: CARDS, old: "import { Icon } from \"./icons\";\n", new: "import { Icon } from \"./icons\";\nconst CardButton = (p: Record<string, unknown>) => <button {...p} />; // MUT-45\n" },
    ] },
  { id: "MUT-46", guard: "RequestCard 的 key 是 request_id", expect: ["TG-17", "TX-14b"], targets: [ALL, e2e("TX-14b")], note: "N34：TX-14 杀不死（答复即 disabled、焦点离开，第二次 Enter 无论 key 对错都落空），真正可观测的是组件状态串卡——假进程版 TX-14b 断言第一张卡的反馈不被第二张继承", file: CARDS,
    old: "      {requests.map((req) => (\n        <RequestCard key={String(req.request_id)}", new: "      {requests.map((req, i) => (\n        <RequestCard key={i}" },
  { id: "MUT-47", guard: "host 缺席 / 不应答时直接退出", expect: ["TX-8b"], targets: [real("TX-8b 真实"), real("TX-8b② 真实")], file: MAIN,
    old: "    if (!host || !hostReady || fatal !== null) {\n      quitting = true;\n      return;\n    }\n    e.preventDefault();\n    quitPhase = \"querying\";\n    sendToHost({ type: \"quit-query\" });\n    quitQueryTimer = setTimeout(() => {\n      quitting = true;\n      app.exit(0);\n    }, QUIT_QUERY_TIMEOUT_MS);",
    new: "    e.preventDefault(); // MUT-47\n    quitPhase = \"querying\";\n    sendToHost({ type: \"quit-query\" });" },
  { id: "MUT-48", guard: "window-all-closed 不先发 shutdown", expect: ["TX-8d"], targets: [real("TX-8d ")], file: MAIN,
    old: "    app.quit(); // 不再先发 shutdown", new: "    sendToHost({ type: \"shutdown\" }); // MUT-48\n    app.quit(); // 不再先发 shutdown" },
  { id: "MUT-49", guard: "退出状态机防重入", expect: ["TX-8c"], targets: [real("TX-8c ")], file: MAIN,
    old: "  app.on(\"before-quit\", (e) => {\n    if (quitPhase !== \"idle\") {", new: "  app.on(\"before-quit\", (e) => {\n    if (false) { // MUT-49" },
  { id: "MUT-50", guard: "回合结算等 stop_points 与更晚的读取", expect: ["TH-20", "TX-5"], targets: [ALL, real("TX-5 ⑤")], file: SESS,
    old: "        this.registerSettle(s, String(f.turn_id));\n",
    new: "        this.append(s, { k: \"settled\", at: this.deps.now(), turnId: String(f.turn_id), timedOut: false }); // MUT-50\n" },
  { id: "MUT-51", guard: "generation 带 hostBootId", expect: ["TH-19"], targets: [ALL], file: SESS,
    old: "      generation: `${this.deps.bootId}:${this.n}`,\n      phase: \"starting\",", new: "      generation: `${this.n}`, // MUT-51\n      phase: \"starting\",",
    note: "TV-10 是 convStore 的纯 reducer 用例（喂显式 generation），host 侧变异打不到它；只期望 TH-19" },
  { id: "MUT-52", guard: "choosing 期间拦 conv.send", expect: ["TH-13"], targets: [ALL], file: SESS,
    old: "    if (this.deps.blocked()) this.fail(\"E_BUSY\", \"正在切换仓库\");\n    if (text === \"\")", new: "    // MUT-52\n    if (text === \"\")" },
  { id: "MUT-55", guard: "created_at 按时间比较（非字符串）", expect: ["TV-6"], targets: [ALL], file: AUTO,
    old: "  for (const o of items) if (compareIso(o.created_at, best.created_at) >= 0) best = o;", new: "  for (const o of items) if (o.created_at >= best.created_at) best = o; // MUT-55",
    note: "TV-11 是 compareIso 自身的用例，这里改的是调用点；期望 TV-6 红" },
  { id: "MUT-56", guard: "会话夹具改写 config/agent.local.json", expect: ["TF-2"], targets: [{ vitest: ["tests/host/sessionFixtures.test.ts"] }], file: FIX,
    old: "  fixtureWrite(root, \"config/agent.local.json\", JSON.stringify({ base_url: baseUrl, model: \"fake\", api_key_env: \"AVA_TEST_KEY\" }, null, 2));\n", new: "  // MUT-56\n" },
  { id: "MUT-57", guard: "原生确认框只对批准弹", expect: ["TH-18"], targets: [ALL], file: "src/shared/nativeConfirm.ts",
    old: "  if (decision !== \"approve\" || req.t !== \"request\") return false;", new: "  if (req.t !== \"request\") return false; // MUT-57" },
  { id: "MUT-58", guard: "一个处理器至多一处答复调用", expect: ["TG-4′"], targets: [ALL], file: CARDS,
    old: "              setBusy(true);\n              setError(null);\n              void rpc\n                .call(\"conv.answer\"",
    new: "              setBusy(true);\n              setError(null);\n              void rpc.call(\"conv.answer\", { convKey, requestId, decision }); // MUT-58\n              void rpc\n                .call(\"conv.answer\"" },
  { id: "MUT-59", guard: "零停机点回合也推进结算", expect: ["TH-20"], targets: [ALL], file: SESS,
    old: "        if (s.settle && tid !== null && tid === s.settle.turnId) {", new: "        if (s.settle && tid !== null && tid === s.settle.turnId && Array.isArray(f.items) && (f.items as unknown[]).length > 0) { // MUT-59" },
  { id: "MUT-60", guard: "结算以读取开始时刻比较", expect: ["TH-20"], targets: [ALL], file: SESS,
    old: "    if (readStart <= s.settle.after) return;", new: "    if (this.deps.now() <= s.settle.after) return; // MUT-60" },
  { id: "MUT-61", guard: "结算超时兜底", expect: ["TH-20"], targets: [ALL], file: SESS,
    old: "      this.settleNow(s, true);\n    }, this.timing.settleMs);", new: "      void 0; // MUT-61\n    }, this.timing.settleMs);" },
  { id: "MUT-62", guard: "onConnect 重置 autoOpen", expect: ["TV-6"], targets: [ALL, real("TX-15")], file: APP,
    old: "      autoRef.current = step(autoRef.current, { kind: \"reset\", phase: \"none\", turnId: null, settlePending: null }, { mediaPlaying: false }).state;\n      setStrip(null);",
    new: "      setStrip(null); // MUT-62",
    note: "N34 判为等价变异（预期 SURVIVED）：重连后 fetchConv(当前会话键, resetAuto=true) 以新 host 的 snapshot 再做一次同样的 reset，两次之间没有可达的 pendings 事件（episode.activate 要 spawn STATUS，慢于 episodes.list→conv.snapshot 两跳）；只有这两次 RPC 失败时 onConnect 的同步 reset 才有差别。两处 reset 都去掉的 MUT-62′ 由 TX-15b 杀死" },
  { id: "MUT-62′", guard: "host 重连后 autoOpen 的 awaiting 被重建（两处 reset 一起失效）", expect: ["TX-15b"], targets: [e2e("TX-15b")],
    edits: [
      { file: APP, old: "      autoRef.current = step(autoRef.current, { kind: \"reset\", phase: \"none\", turnId: null, settlePending: null }, { mediaPlaying: false }).state;\n      setStrip(null);", new: "      setStrip(null); // MUT-62′" },
      { file: APP, old: "          if (resetAuto && snap.convKey === convKeyRef.current) applyAuto(", new: "          if (false /* MUT-62′ */ && resetAuto && snap.convKey === convKeyRef.current) applyAuto(" },
    ] },
  { id: "MUT-63", guard: "确认框正文转义不可见字符", expect: ["TH-18"], targets: [ALL], file: "src/shared/nativeConfirm.ts",
    old: "  const escaped = body.map((line) => escapeInvisible(line));", new: "  const escaped = body.map((line) => ({ text: line, count: 0 })); // MUT-63" },
  { id: "MUT-64", guard: "确认框 reqId 带 bootId、host 退出即 abort", expect: ["TH-22"], targets: [ALL],
    edits: [
      { file: "src/host/confirm.ts", old: "      const reqId = `${deps.bootId}:${seq}`;", new: "      const reqId = `${seq}`; // MUT-64" },
      { file: "src/main/confirm.ts", old: "      active?.abort();", new: "      void active; // MUT-64" },
    ] },
  { id: "MUT-65", guard: "quit-proceed 后拒绝 conv.send", expect: ["TH-21"], targets: [ALL], file: SESS,
    old: "  async send(key: ConvKey, target: SessionTarget, text: string): Promise<{ turnId: string }> {\n    if (this.quitting) this.fail(\"E_BUSY\", \"正在退出\");\n",
    new: "  async send(key: ConvKey, target: SessionTarget, text: string): Promise<{ turnId: string }> {\n    // MUT-65\n" },
  { id: "MUT-66", guard: "fixtureWrite 对目标本身也 lstat", expect: ["TF-1"], targets: [{ vitest: ["tests/host/sessionFixtures.test.ts"] }], file: FIX,
    old: "  for (const seg of relPath.split(sep)) {", new: "  for (const seg of relPath.split(sep).slice(0, -1)) { // MUT-66" },
  { id: "MUT-67", guard: "stop_points 不要求紧跟 turn_finished", expect: ["TH-20"], targets: [ALL, real("TX-5 ⑤")], note: "真实 core 版 TX-5⑤ 里 05 pending 在回合中就被 heal 建好，回合末 ensure_pending 不新建、两帧之间没有 log，这条变异在那里无从暴露；由 TH-20⑥ 看守", file: SESS,
    old: "        if (s.settle && tid !== null && tid === s.settle.turnId) {",
    new: "        const prevMut67 = s.entries[s.entries.length - 2];\n        if (s.settle && tid !== null && tid === s.settle.turnId && prevMut67?.k === \"frame\" && prevMut67.frame.t === \"turn_finished\") { // MUT-67" },
  { id: "MUT-68", guard: "R6 从 snapshot 重建 awaiting", expect: ["TV-6"], targets: [ALL], file: AUTO,
    old: "      const awaiting = ev.phase === \"running\" ? ev.turnId : ev.settlePending;", new: "      const awaiting = null; // MUT-68" },
  { id: "MUT-69", guard: "browser 确认框：目标行在理由之前、不整段转储 args", expect: ["TH-18"], targets: [ALL], file: "src/shared/nativeConfirm.ts",
    old: "  return [`操作：${str(args.action)}`, `目标：${target}`, FREE_TEXT_LABEL, clipText(str(args.reason))];", new: "  void target;\n  return [clipText(JSON.stringify(args))]; // MUT-69" },
  { id: "MUT-70", guard: "每个会话键只有一个待结算槽位", expect: ["TH-20"], targets: [ALL], file: SESS,
    old: "        if (s.settle && tid !== null && tid === s.settle.turnId) {",
    new: "        if (tid !== null && (!s.settle || tid !== s.settle.turnId) && s.entries.some((e) => e.k === \"frame\" && e.frame.t === \"turn_finished\" && e.frame.turn_id === tid)) this.append(s, { k: \"settled\", at: this.deps.now(), turnId: String(tid), timedOut: false }); // MUT-70\n        if (s.settle && tid !== null && tid === s.settle.turnId) {" },
  { id: "MUT-71", guard: "结算按 stop_points.turn_id 精确匹配", expect: ["TH-20"], targets: [ALL], file: SESS,
    old: "        if (s.settle && tid !== null && tid === s.settle.turnId) {", new: "        if (s.settle && tid !== null) { // MUT-71" },
  { id: "MUT-72", guard: "能力缺席 / 不可达时立即结算", expect: ["TH-20"], targets: [ALL], file: SESS,
    old: "    return this.deps.canReadApprovals(epKey); // 能力缺席或不可达", new: "    return true; // MUT-72 能力缺席或不可达" },
  { id: "MUT-73", guard: "R6 用 settlePending 重建 awaiting（不扫条目）", expect: ["TV-6"], targets: [ALL], file: AUTO,
    old: "      const awaiting = ev.phase === \"running\" ? ev.turnId : ev.settlePending;", new: "      const awaiting = ev.phase === \"running\" ? ev.turnId : null; // MUT-73",
    note: "变体：现实现的 reset 事件不带条目，无法表达「扫描 entries」；以其后果（丢失 settlePending 分支）植入" },
];
